"""longitude corruption

Revision ID: b1ee7d78bae9
Revises: d90281c621bb
Create Date: 2018-02-23 10:15:58.575522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ee7d78bae9'
down_revision = 'd90281c621bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crime', sa.Column('longitude', sa.Float(precision=10, asdecimal=6), nullable=True))
    op.drop_column('crime', 'longtitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crime', sa.Column('longtitude', sa.REAL(), autoincrement=False, nullable=True))
    op.drop_column('crime', 'longitude')
    # ### end Alembic commands ###
